### ISSUE TITLE
Petició de col·laboració: foto d'un tió

### ISSUE THREAD

**Issue by kamencesc** [oooriii/divendres-ori#1]
La he liado parda y pido disculpas

**Comment by oooriii** [comment]
M'agradaria que al meu repositori hi hagués una foto d'un tió

**Comment by oooriii** [comment]
Estaria bé que el repo tingués una llista dels convidats al banquet de Nadal

**Comment by ctrl-alt-d** [comment]
jo faré la foto del tió !
